enterButtonsId.addEventListener("click", onClickButtons)
loginId.addEventListener("blur", onBluRegistration, true)
registrationId.addEventListener("blur", onBluRegistration, true)
regBtnsId.addEventListener("click", onClickRegBtns)
loginBtnsId.addEventListener("click", onClickRegBtns)
exitId.addEventListener("click", onClickExit)
